Change grip method to return bool
robofit/arcor2 pull request #521
Opened 2021-04-15 11:42 UTC by Croolman

Updated API of abstract robot to reflect Robot 0.10.0 [changes](https://gitlab.com/kinalisoft/test-it-off/robot).

2021-04-15 12:03 UTC, ZdenekM commented on src/python/arcor2_kinali/object_types/abstract_robot.py
>              params={"position": position, "speed": speed, "force": force},
@Croolman Please add there `return_type=bool`. Otherwise, mypy (type checking) will complain :-)

2021-04-15 12:06 UTC, Croolman commented on src/python/arcor2_kinali/object_types/abstract_robot.py
>              params={"position": position, "speed": speed, "force": force},
@ZdenekM Will do.

2021-04-15 12:13 UTC, ZdenekM commented
@Croolman This time, there is a problem with formatting. I would suggest running `./pants fmt path_to_changed_file` to fix it. You can also check if formatting is ok by using `./pants lint path_to_changed_file`.

2021-04-15 12:38 UTC, ZdenekM requested changes

2021-04-15 12:38 UTC, ZdenekM commented on src/python/arcor2_kinali/object_types/abstract_robot.py
> +            params={"position": position, "speed": speed, "force": force}, return_type=bool
It should be on the new line. We have quite strict rules for formatting but fortunately, our tooling can do formatting automatically (`./pants fmt file`).

2021-04-15 14:53 UTC, Croolman commented on src/python/arcor2_kinali/object_types/abstract_robot.py
> +            params={"position": position, "speed": speed, "force": force}, return_type=bool
I have tried that, but did not manage to make it run (many dependencies issues). I have run it successfully now from within the `arcor2_devel` docker though.

2021-04-16 05:18 UTC, Croolman commented
@ZdenekM Can you please check the failed build? We have had encountered the similiar issues before. A rebuild often helps on our side (as a workaround)

2021-04-16 06:02 UTC, ZdenekM commented
@Croolman Sorry for the trouble, I hoped that this is already fixed and will not happen again. I was foolish :) Re-running the job should help for now.

2021-04-16 06:38 UTC, Croolman commented
@ZdenekM No worries. All seems to be good to go now.

2021-04-16 06:55 UTC, merged