Visualization action points
robofit/arcor2 pull request #705
Opened 2022-01-17 16:37 UTC by ChrnyaevEK

This is a merge request for AP visualization, as we have discussed.

Basically I have changed `ActionStateBefore` event scheme, then I have updated runtime `@action` decorator to get AP ids from arguments. Due to this change the `ActionStateBefore` will be dispatched for each action (with or without id or any pose/joints in arguments). This event will be than handled by rest proxy. 

At rest proxy I have added 2 global variables to hold last action state - one for `ActionStateBefore.Data` and another for `ActionStateAfter.Data`, just like you hold `package_state` for example. `ActionStateAfter` will be unset once `ActionStateBefore` is met (at this moment `ActionStateAfter` already belongs to previous action), however `ActionStateBefore` will never be unsettled once set. We have discussed internally, that it is ok, that information about the last AP will remain (will not be unset), even when script state is "Completed" or action has ended (`ActionStateAfter` was fired). `ExecutionInfo` and `packeges/executioninfo` were updated to return AP ids.

As well I have updated tests for `arcor_runtime`, but I guess you might want to check some other things here, so it is an open question what tests should be done.

I ran tests for related services. I did not manage to run typecheck and tests for all services due to (I suppose) `pyk4a`.

2022-01-17 16:39 UTC, ChrnyaevEK commented on src/python/arcor2_execution_rest_proxy/scripts/execution_rest_proxy.py
> +
I tried to use `try...except` here, but type checking failed with "None" has no attribute...

2022-01-17 16:39 UTC, ChrnyaevEK commented on src/python/arcor2_runtime/action.py
> +                    action_point_ids.append(getattr(aa, AP_ID_ATTR))
Should we check other types, like Orientation or Position?

2022-01-18 08:32 UTC, ZdenekM requested changes
Thanks for your effort, it certainly looks good.

2022-01-18 08:32 UTC, ZdenekM commented on src/python/arcor2_execution_rest_proxy/scripts/execution_rest_proxy.py
> +
You mean `try...except` to catch what? I guess it should not be necessary here, unless I missed something :-) Btw, you can simplify `if action_state_before is not None:` to just `if action_state_before:` here safely.

2022-01-18 08:32 UTC, ZdenekM commented on src/python/arcor2/data/events.py
> +        action_id: Optional[str]
Please add a default value (`=None`).

2022-01-18 08:32 UTC, ZdenekM commented on src/python/arcor2/data/events.py
>          parameters: List[str]
This should be also optional and have a default value, e.g. `parameters: Optional[List[str]] = None`.

2022-01-18 08:32 UTC, ZdenekM commented on src/python/arcor2/data/events.py
> +        action_point_ids: List[str]
Make it optional with a default value.

2022-01-18 08:32 UTC, ZdenekM commented on src/python/arcor2_runtime/action.py
> +        action_point_ids = []
Please add type annotation.

2022-01-18 08:32 UTC, ZdenekM commented on src/python/arcor2_runtime/action.py
> +                    action_point_ids.append(getattr(aa, AP_ID_ATTR))
I think that it is ok to check just `Pose` (actually its `position` property, see the original code) and `ProjectRobotJoints` - only these two types are patched with the `AP_ID_ATTR`. We don't support (at the moment) parameters of type `Orientation` or `Position` anyway.

2022-01-18 08:32 UTC, ZdenekM commented on src/python/arcor2_runtime/action.py
> +        # dispatch even if action id was not detected
dispatch even**t** :)

2022-01-18 08:53 UTC, ZdenekM commented
If you have problems with `pyk4a`, get rid of `arcor2_kinect_azure`, remove `pyk4a` from `requirements.txt` and you should be fine. Another option is to install it (we have a [script](https://github.com/robofit/arcor2/blob/master/build-support/install_kinect_prerequisites.sh) for that, certainly works on Ubuntu 18.04).

Regarding tests, I guess that it will be also necessary to update [arcor2_arserver/tests/test_project_execution.py](https://github.com/robofit/arcor2/blob/master/src/python/arcor2_arserver/tests/test_project_execution.py).

And the last thing - please squash your commits and follow https://www.conventionalcommits.org/en/v1.0.0/.

2022-01-18 15:16 UTC, ZdenekM commented
@ChrnyaevEK Sorry for the trouble, in the meantime, I've made some changes regarding switching to Python 3.9, which caused some conflicts... Please rebase your branch.

2022-01-19 07:29 UTC, ZdenekM commented on src/python/arcor2/data/events.py
> +        action_point_ids: Optional[List[str]] = None
Well, actually `set[str]` after the switch to 3.9...

2022-01-19 09:51 UTC, ChrnyaevEK commented on src/python/arcor2_execution_rest_proxy/scripts/execution_rest_proxy.py
> +
Well, yes, [this](https://docs.python.org/3.6/glossary.html#term-eafp) is not really necessary here, agree. But I would leave `if action_state_before is not None` as it is recommended to use `is` when comparing with `None`  ([PEP 8](https://www.python.org/dev/peps/pep-0008/#programming-recommendations))

2022-01-19 09:53 UTC, ChrnyaevEK commented on src/python/arcor2/data/events.py
> +        action_point_ids: Optional[List[str]] = None
Agree. Will be updated with next commit

2022-01-19 12:28 UTC, ZdenekM commented
@ChrnyaevEK Tests failed due to some rare race condition (not because of your changes), that should be hopefully fixed in https://github.com/robofit/arcor2/pull/708.

2022-01-19 12:31 UTC, ChrnyaevEK commented
@ZdenekM Thanks! At least I have installed pyk4a to check it locally and locally it succeeded

2022-01-19 12:59 UTC, ZdenekM approved these changes

2022-01-19 13:10 UTC, merged