second version of python_to_json
robofit/arcor2 pull request #806
Opened 2023-02-14 17:16 UTC by SimonKadnar

I had trouble whit that import cycle so i created a new file "python_to_json.py" (i am not sure how to solve this problem) and i added some little tests in zip packages (all should work).

2023-02-16 09:15 UTC, ZdenekM requested changes
- Please run `./pants fmt ...` and then solve errors reported by `lint` and `check` goals before creating a PR. 
- You don't need to close existing PR and create a new one. Update your commits, or add new ones and push to your fork. The opened PR will be updated accordingly.
- Not sure whether it is good to have execution packages as `zip` files - what about keeping it as a directory/module and making it into `zip` in runtime (if it is really needed)?

2023-02-16 09:16 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_logic.py
> +    for k in range(len(project.action_points)):
Why not just `for ap in project.action_points:`?

2023-02-16 09:18 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_logic.py
> +    for i in project.logic:
`i` is usually an index. Please use something more descriptive here, like `logic_item`, or at least `li`.

2023-02-16 09:19 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_logic.py
> +def find_action_from_name(name: str, project: Project):
This should be the method of `CachedProject`.

2023-02-16 09:20 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_logic.py
> +def find_action_from_id(id: str, project: Project):
`CachedProject` already has a method for this.

2023-02-16 09:21 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_logic.py
> +    raise "Action whit id:"+id+" in project:"+project.name+"does not exisit"
This is not allowed in Python 3.10. Moreover, all exceptions should be based on `Arcor2Exception`.

2023-02-16 09:27 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +def find_Call(tree: Union[Module, AST]) -> Call:
These helper functions could go somewhere else... Like `arcor2_build/source/utils.py` or `arcor2_build/source/helpers.py`?

2023-02-16 09:31 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +        except:
`except:` or `except Exception:` should be definitely avoided.

2023-02-16 09:34 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    ap = ActionPoint("#ap", Position())
What this `ap` is good for?

2023-02-16 09:37 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    variables: dict[str, str] = {}
This should go to `CachedProject` or to a separate module/class within `arcor2_build`.

2023-02-16 18:21 UTC, SimonKadnar commented on src/python/arcor2_build/source/python_to_json.py
> +    ap = ActionPoint("#ap", Position())
Ap is action point where shoud by stored new generated actions . If in some fuction is used global action point "ap" will remeber this action point a then next actions are stored here but on start i do not have this action point so i must put there smothing. Maybe i can put there the first action point from project and not put there some empty point.

2023-02-16 19:04 UTC, SimonKadnar commented
I was thinking the entry parameter in this program will be zip file so i created zip files for complet testing but i can change it into files but then i have to create a new function for reading files just for tests or if i understand wrongly the entry parameter i can change function for read from zip into read from files and change the tests.

2023-02-20 12:40 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_logic.py
> +    for file in test_files:
Take a look here: https://docs.pytest.org/en/6.2.x/parametrize.html or here for https://github.com/robofit/arcor2/blob/master/src/python/arcor2/tests/test_helpers.py#L9

2023-02-20 12:45 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +def get_pro_sce_scr(file: str):
Not a priority now, but please note that this should go somewhere else... Now the same (or almost the same) code is also in `scripts/build.py`.

2023-02-20 12:48 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    type = plugin_from_type_name("boolean")
Why is there hardcoded `boolean`?

2023-02-20 12:49 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    for i in range(len(original_project.action_points)):
Unnecessary index :)

2023-02-20 12:50 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    print(variables)
For debugging purposes, I would suggest using a logger, that is silent by default and can be turned on using an environment variable, like here: https://github.com/robofit/arcor2/blob/master/src/python/arcor2_build/source/logic.py#L38

2023-02-20 12:55 UTC, ZdenekM commented
> I was thinking the entry parameter in this program will be zip file so i created zip files for complet testing but i can change it into files but then i have to create a new function for reading files just for tests or if i understand wrongly the entry parameter i can change function for read from zip into read from files and change the tests.

Correct, the input will be a zip file. So for tests, you can create one from files... Maybe it can be done as a fixture? Should be easy - just zipping the directory...

2023-02-20 15:42 UTC, SimonKadnar commented on src/python/arcor2_build/source/python_to_json.py
> +    type = plugin_from_type_name("boolean")
Value in condition in program, is usually True or False so i thought there will be always boolean type

2023-02-20 16:15 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    type = plugin_from_type_name("boolean")
Yes, so far, there are only boolean, but (one day) there might be, for instance enums, integers...

2023-02-20 16:16 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    type = plugin_from_type_name("boolean")
Would be nice to have it prepared.

2023-02-20 20:37 UTC, SimonKadnar commented
Hmmm iteresting but that file is there and localy it works

2023-02-20 20:46 UTC, SimonKadnar commented
I tried download my branch and everything is working i am not sure where can by the issue

2023-02-22 07:34 UTC, ZdenekM commented
@SimonKadnar Could you please add just one commit for each iteration? Like this, it's quite hard to check what has been changed since the last time. Thanks.

2023-02-22 07:41 UTC, ZdenekM requested changes

2023-02-22 07:41 UTC, ZdenekM commented on src/python/arcor2/cached.py
> +    def find_logic_start_end(self, start: str, end: str) -> cmn.LogicItem:
There is already highly similar method, see https://github.com/robofit/arcor2/blob/master/src/python/arcor2/cached.py#L473

2023-02-22 07:41 UTC, ZdenekM commented on src/python/arcor2/cached.py
> +        raise Arcor2Exception("Action whit name:" + name + " in project:" + self.name + "does not exisit")
multiple typos

2023-02-22 07:41 UTC, ZdenekM commented on src/python/arcor2/cached.py
> +        raise Arcor2Exception("Action whit name:" + name + " in project:" + self.name + "does not exisit")
Please use f-string to compose messages like this.

2023-02-22 07:41 UTC, ZdenekM commented on src/python/arcor2/parameter_plugins/boolean.py
> +        if value == "True":
What about `str(True)` instead of `"True"`?

2023-02-22 07:41 UTC, ZdenekM commented on src/python/arcor2/parameter_plugins/boolean.py
> +        if value == "True":
And maybe use a mapping instead of if-elif?

2023-02-22 07:41 UTC, ZdenekM commented on src/python/arcor2/parameter_plugins/boolean.py
> +        return ""
Raise an error instead?

2023-02-22 07:41 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_fodlers/test_const/action_points.py
> +from arcor2.data.common import ActionPoint, Position
There is a typo in path (test_fodlers).

2023-02-22 15:18 UTC, SimonKadnar commented on src/python/arcor2/cached.py
> +    def find_logic_start_end(self, start: str, end: str) -> cmn.LogicItem:
i have feeling you choose wrong method because its returning value is action id, find_logic_start_end() is about returning specific logic item

2023-02-25 12:38 UTC, SimonKadnar commented
I know you said less commits but i did it during 3 days and i find little problem in tests :  when is imported same class more times it creates some mess in dict where are stored objects types, so i tried test like this i take value from your function (program_src) and i am using it as modified script as input in to my program. I am not sure how test thats modules when they include same classes, maybe if exists some function to clean imported files it can workes but i can create tests like this whitout reading zip file but what you think shoud i crate more tests and put there script like string or use your function to translade it and then test it ?

2023-02-27 09:24 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +def get_type(rest_of_node: Call, scene: Scene):
If I got it right... You have something like `robot.move()`, and you want to get `Robot`, right? I would add to `CachedScene` something like `get_object_by_name` (names are required to be unique) returning `SceneObject`.

2023-02-27 09:24 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +
You should raise an exception if you don't find it...

2023-02-27 09:24 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +        object = object_method[:dot_position]
`object` is not a good name for variable (it's a type in Python).

2023-02-27 09:24 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +# add Logic item in case that before was "if"
This should be docstring.

2023-02-27 09:24 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    except KeyError:
Where does `KeyError` come from?

2023-02-27 09:24 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_logic.py
> +# for this test every name of action must be unique
That's our assumption everywhere, not just for this test.

2023-02-27 09:24 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +def between_step(project: Project, scene: Scene, script: str, object_type: dict):
Could this have more descriptive name and docstring?

2023-02-27 09:27 UTC, ZdenekM commented
> I know you said less commits but i did it during 3 days and i found little problem in tests : when is imported same class more times it creates some mess in dict where are stored objects types, so i tried test like this i take value from your function (program_src) and i am using it as modified script as input in to my program. I am not sure how test thats modules when they include same classes, maybe if exists some function to clean imported files it can workes but i can create tests like this whitout reading zip file but what you think shoud i crate more tests and put there script like string or use your function to translade it and then test it ?

Not sure what the problem is. We should discuss it in person or during a call.

2023-03-03 07:50 UTC, ZdenekM commented on src/python/arcor2/cached.py
> +    # find specific LogicItem whit start parameter and end parameter
This should be a docstring.

2023-03-03 07:50 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +POSES = "poses"  # TODO: place somewhere else as constants
Maybe `arcor2_build/source/__init__.py`?

2023-03-03 07:50 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +""" add logic item for common case (calling method...)
Make it into a docstring.

2023-03-03 07:50 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +def python_to_json(project: Project, scene: Scene, script: str, object_type: dict):
Missing type annotation for the return value.

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +            if param_type == "" and param_value == "":
It could be simply `if not (param_type or param_value)`.

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +        elif isinstance(arg, Name):  # variable definated in script or variable from project parameters
Please pay attention also to typos (PyCharm highlights them), here "definated".

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +                raise Arcor2Exception("Value type in method is not equal required value type")
Please use e.g. Grammarly for texts.

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +# debug function
Could you remove such comments or make them into meaningful docstrings? Btw, if the function is going to stay, you might make it into the `Project` method - something like `def pretty_print()`? And use e.g. `for ap in project.action_points`...

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +def zip_package(folder: str):  # TODO: place somewhere else
`TODO: place somewhere else` do that :-)

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +def between_step(zip_file) -> Project:
This is not used anywhere... Remove it?

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    """if condition is on, then in future when should by generated new
This is a bit hard to understand, but if I got it right, you made a preparation to allow having two `if ... elif` blocks in a row. I think that's not going to happen - the JSON representation does not allow it. So I wouldn't make the code more complicated because of that.

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_compiler_str.py
> +class Test_class(StrEnum):
Rather `TestEnum`? Definitely, class names should be in `PascalCase` (no underscores).

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/tests/test_compiler_str.py
> +def action_from_id(action_id: str, project: CachedProject) -> Action:  # TODO: replace
`# TODO: replace` do it :-)

2023-04-14 07:45 UTC, ZdenekM commented on src/python/arcor2_build/source/utils.py
> +from typing import Union
Can't you use `|` instead of `Union`?

2023-04-14 22:41 UTC, SimonKadnar commented
I itegrated compiler into build.py but i am not sure if i did it right. One of necessarys values for decompile is script but you importining it only if project has no logic so i added another condition whit difrenet variable for script, to do not affect rest of function. Now decompilation works when you set to owerrite script.

2023-04-16 18:03 UTC, SimonKadnar commented on src/python/arcor2_build/source/python_to_json.py
> +    """if condition is on, then in future when should by generated new
No exactly, that case is catched in instance of "If" as error. If that variable "condition" is true then function knows the last generated action was in "if" or "elif" and that is important information for generating LogicItems.

2023-04-17 06:24 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    """if condition is on, then in future when should by generated new
Ok, I see.

2023-04-17 06:27 UTC, ZdenekM commented
That should be a good solution I guess.

2023-04-17 07:15 UTC, ZdenekM reviewed
Please focus on adding missing annotations, docstrings, and their comprehensibility and typos - I picked up some of them, but there are many.

2023-04-17 07:15 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    position get END of last ac_id and new logic item get ac_id on START."""
Rephrase the docstring. Very hard to read and understand.

2023-04-17 07:15 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +        raise Arcor2Exception('Condition must by in from: if "variable" == "value":')
typos

2023-04-17 07:15 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    variables: dict[str, str] = {}  # TODO: separate module/class within arcor2_build /function
What do you mean by "variables" - variables holding return values?

2023-04-17 07:15 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    action_point: ActionPoint,
Add also a description of arguments - here, it is not easy to get what is e.g. `action_point` good for.

2023-04-17 07:15 UTC, ZdenekM commented on src/python/arcor2_build/source/utils.py
> +class a_p_const:
Enum with some more descriptive name (e.g. `SpecialValues`)?

2023-04-17 20:34 UTC, SimonKadnar commented on src/python/arcor2_build/source/python_to_json.py
> +    action_point.actions.append(ac1)  # add actions to last seen action_point
Yes but when you add some action, program need some information where action should be placed, so i created this last seen action point where action should be placed.

2023-04-17 21:09 UTC, SimonKadnar commented on src/python/arcor2/cached.py
> +            if object_method.find(scene_object.name + ".") != -1:
It is a complet name of obejct and method e.g. dobot_magician.pick "dobot_magician" and "pick" so object_method = "dobot_magician.pick" and then lets say dobot_magician has id= 123456789 then return value from this function is "1234456789/pick"

2023-04-18 19:38 UTC, SimonKadnar commented
I will fix that typos and other stuff later. I did this commit because i want have actual version for tomorrow

2023-04-24 17:59 UTC, SimonKadnar commented
I tried do squesh but it creates a big errors and conflicts. I not sure why when you take them all together i expect it will be fine but not. Wudnt be better delete all commits and then create one with actuall version because i dont know how to fix this ?

2023-04-27 10:02 UTC, ZdenekM commented on src/python/arcor2/cached.py
> +    def get_object_by_name(self, object_method: str):
> i am not sure how do you want use that function

Well, it could be used to make Build aware of what actions with what parameters each ObjectType has. But never mind, it's too late to implement it. You could mention it in future work.

2023-04-27 10:05 UTC, ZdenekM commented on src/python/arcor2_build/source/python_to_json.py
> +    variables: dict[str, str] = {}  # TODO: separate module/class within arcor2_build /function
Ok, I see. I suggest mentioning somewhere that those are the results of actions so that they won't get confused with something else.

2023-04-27 20:10 UTC, SimonKadnar commented
I created integration test but its for docker. I tried to make it like you said but in that way i am little lost. Maybe if you have time tomorrow we can try resolvit during the call. After this i can change that action point staff... but that shoud be all for this ''pull request''.

2023-04-30 12:26 UTC, SimonKadnar commented
> > I tried do squesh but it creates a big errors and conflicts. I not sure why when you take them all together i expect it will be fine but not. Wudnt be better delete all commits and then create one with actuall version because i dont know how to fix this ?
> 
> Have you tried to rebase first? E.g. with `git pull --rebase`. There shouldn't be many conflicts, maybe just a few, as there was no active development in the `arcor2/master`. Conflicts are normal and should be quite easy to solve in this case.

Yes and it writing me "already up to date" but when i try "git rebase  --interactive abe9d9f" (abe9d9f is my first commit) it giving me nonstop new and new conflicts that i have to resolve and after i resolve it giving me again new conglicts.

2023-05-03 06:12 UTC, closed without merging