Prvy PR
robofit/arcor2 pull request #811
Opened 2023-03-07 16:33 UTC by xlukac16

Kod nie je spustitelny zo zlozky, v ktorej sa nachadza kvoli tomu, ze pozaduje zavislosti na kode v baliku arcor2, arcor2_server_data.

2023-03-09 09:23 UTC, ZdenekM requested changes
Please look at other `arcor2` packages - you are missing `BUILD` files and some of the structure. Also, please don't forget to run `./pants fmt ::`, `./pants lint ::` and `./pants check ::` and fix errors before making/updating a PR. Btw, when making changes, you can update the existing commit and force push or add new commits... There is no need to make a new PR. Please make changes often and discuss everything that is unclear to speed it up.

2023-03-09 09:23 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/ARServer.py
> +class ARServer:
Why not just import the client from https://github.com/robofit/arcor2/blob/master/src/python/arcor2_arserver_data/client.py? This is code duplication...

2023-03-09 09:23 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseClass.py
> +import pyspacemouse
Dependencies on 3rd party packages should go to https://github.com/robofit/arcor2/blob/master/3rdparty/requirements.txt

2023-03-09 09:23 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +        playsound("speech.mp3",True)
If it is necessary to save the same file for playback, please do it as a temporary file. But I guess playing a file just from memory should be possible without saving it. Please double-check this :-)

2023-03-09 09:23 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/installs.txt
> +pip install gTTS
These lines belong to https://github.com/robofit/arcor2/blob/master/3rdparty/requirements.txt.

2023-03-16 15:21 UTC, ZdenekM commented
@xlukac16 Any update on this?

2023-03-21 10:19 UTC, ZdenekM requested changes

2023-03-21 10:19 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +        ).data
Here, you are returning `data`, not a `Response`.

2023-03-21 10:19 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +    def robot_end_effectors_get(self, g_robot_id: str, g_arm_id: str = None) -> RPC.Response:
Shouldn't be return type annotation rather `srpc.r.GetEndEffectors.Response`?

2023-03-21 10:19 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +        ).data
And btw, aren't that helper functions useless? It does nothing, just calling RPC, which can be probably done directly from where it is needed. Or do you have some further plans with these helper functions (like adding handling of a failure, etc)?

2023-03-21 10:19 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +    def parse_robot_meta(self) -> list:
This could be a one-liner (see list comprehensions).

2023-03-21 10:19 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +        for obj in self.cur_scene["objects"]:
Why do you work with the scene in form of a dictionary? From the event, you got an instance of `Scene` dataclass, which can be "upgraded" to `CachedScene` if you need some more useful methods.

2023-03-21 10:19 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +        pos1.orientation = Orientation().from_rotation_vector(0, 0, 0)
Why not just leave the default orientation - it should be the same...

2023-03-21 10:19 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +mouse = MouseProgram()
I would suggest to divide the code into a "library" - files under `arcor2_3D_mouse` and a launchable script under `arcor2_3D_mouse/scripts/something.py`.

2023-03-22 07:41 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +            srpc.p.AddAction.Request(get_id(), srpc.p.AddAction.Request.Args(g_action_point_id, g_name, g_type)),
Here, it should be `srpc.p.AddAction.Request.Args(g_action_point_id, g_name, g_type, parameters=[...], [Flow()])`. Parameters depend on the actual action being added...

2023-03-22 07:45 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +            srpc.p.AddAction.Request(get_id(), srpc.p.AddAction.Request.Args(g_action_point_id, g_name, g_type)),
Well... For instance, `move` action of the Dobot Magician has default values for all parameters, so it is (probably) not necessary to deal with parameters :)

2023-03-22 07:48 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +# print(mouse.action_add("acp_783b448e55e446d28210c8aab4752f93","ac1_move","obj_5143000ceec44766b0dda64e422481ab/move"))
Btw, it would be good not to have `"move"` action (or any other) hardcoded... This should go into some configuration file.

2023-04-18 21:02 UTC, xlukac16 commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +# print(mouse.action_add("acp_783b448e55e446d28210c8aab4752f93","ac1_move","obj_5143000ceec44766b0dda64e422481ab/move"))
To len testovacie akcie

2023-04-18 21:47 UTC, xlukac16 commented on src/python/arcor2_3D_mouse/MouseProgram.py
> +            return "no event"
I replaced it with None. I also add checks for None where it was called.

2023-04-21 11:16 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_program.py
> +        langObj.save("speech.mp3")
Please use https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile

2023-04-21 11:16 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_program.py
> +        robot_list = []
Add type annotation (not only here, but everywhere where it is missing).

2023-04-21 11:16 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_program.py
> +            if param_meta.default_value is None and param_meta.name == "move_type":
This "move_type" is specific to a certain robot. It would be good to allow the user/developer to specify which action should be used and with what parameters in a configuration file. To make this SW useful also for different robots.

2023-04-21 11:16 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_program.py
> +            if li.start == "START":
Use `LogicItem.START` instead of `"START"`.

2023-04-21 11:16 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_program.py
> +    def find_last_logic(self, logiclist: list[LogicItem]) -> LogicItem:
Conditions should be handled somehow - at least if the project contains conditions, print something and give up.

2023-04-21 11:16 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_program.py
> +        def_pos.orientation.__mul__(
Why calling `__mul__`? You could do `def_pose.orientation *= some_other_orientation`.

2023-04-21 11:16 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_program.py
> +        def_pos.position.x = def_pos.position.x + g_mouse_reading.x * g_sensitivity
`def_pos.position.x += g_mouse_reading.x * g_sensitivity`

2023-04-21 11:16 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_program.py
> +        # TODO redefine offset base on testing#TODO unregister
You could keep it registered and just ignore received values if you don't need them, or you might use RPC to get the end effector pose - that would be maybe easier for you.

2023-04-21 18:33 UTC, xlukac16 commented on src/python/arcor2_3D_mouse/mouse_program.py
> +    def __init__(self, g_name: str, g_desc: str, g_param: list) -> None:
I use it when variable is a parameter. It should stand for given_variable. Is it a problem?

2023-04-24 07:03 UTC, ZdenekM commented on src/python/arcor2_3D_mouse/mouse_controller.py
> +        if g_mouse_reading.x + self.mouse_menu_offset < 0:
Ok, if it is only used for switching a menu, that makes sense.

2023-04-24 07:14 UTC, ZdenekM commented
I'm not sure why CI is not running for this pull request. I will try and re-open it again to see if it helps. If not, please create a new one.

2023-04-24 07:16 UTC, closed without merging